version: "3"
services:
  ecommerce-exprees:
    container_name: ecommerce-api
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
